
# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
sicurezza:
    key: XXXXXXXXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXXXXXXXXXX