
# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
sicurezza:
    key: XXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXXX