
# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
sicurezza:
    key: XXXXXXXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXXXX