

# ==============================================================
# = Parametri Sicurezza AWS DynamoDb 
# ==============================================================
sicurezza:
    key: XXXXXXXXXXXXXXXX
    secret: XXXXXXXXXXXXXXXXXXXXX